# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NetworkCli.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='NetworkCli.proto',
  package='quickstep',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10NetworkCli.proto\x12\tquickstep\"\x1d\n\x0cQueryRequest\x12\r\n\x05query\x18\x01 \x01(\t\";\n\rQueryResponse\x12\x14\n\x0cquery_result\x18\x01 \x01(\t\x12\x14\n\x0c\x65rror_result\x18\x02 \x01(\t2N\n\nNetworkCli\x12@\n\tSendQuery\x12\x17.quickstep.QueryRequest\x1a\x18.quickstep.QueryResponse\"\x00\x62\x06proto3')
)




_QUERYREQUEST = _descriptor.Descriptor(
  name='QueryRequest',
  full_name='quickstep.QueryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='quickstep.QueryRequest.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=60,
)


_QUERYRESPONSE = _descriptor.Descriptor(
  name='QueryResponse',
  full_name='quickstep.QueryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query_result', full_name='quickstep.QueryResponse.query_result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_result', full_name='quickstep.QueryResponse.error_result', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=121,
)

DESCRIPTOR.message_types_by_name['QueryRequest'] = _QUERYREQUEST
DESCRIPTOR.message_types_by_name['QueryResponse'] = _QUERYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QueryRequest = _reflection.GeneratedProtocolMessageType('QueryRequest', (_message.Message,), dict(
  DESCRIPTOR = _QUERYREQUEST,
  __module__ = 'NetworkCli_pb2'
  # @@protoc_insertion_point(class_scope:quickstep.QueryRequest)
  ))
_sym_db.RegisterMessage(QueryRequest)

QueryResponse = _reflection.GeneratedProtocolMessageType('QueryResponse', (_message.Message,), dict(
  DESCRIPTOR = _QUERYRESPONSE,
  __module__ = 'NetworkCli_pb2'
  # @@protoc_insertion_point(class_scope:quickstep.QueryResponse)
  ))
_sym_db.RegisterMessage(QueryResponse)



_NETWORKCLI = _descriptor.ServiceDescriptor(
  name='NetworkCli',
  full_name='quickstep.NetworkCli',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=123,
  serialized_end=201,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendQuery',
    full_name='quickstep.NetworkCli.SendQuery',
    index=0,
    containing_service=None,
    input_type=_QUERYREQUEST,
    output_type=_QUERYRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_NETWORKCLI)

DESCRIPTOR.services_by_name['NetworkCli'] = _NETWORKCLI

# @@protoc_insertion_point(module_scope)
